### ISSUE TITLE
[BUG] Layout imitation doesn't remap ñ key in Spanish/Latinamerican keyboards

### ISSUE THREAD

**Issue by noquierouser** [nvlgzr/fngrng#12]
# Describe the bug
`Ñ` key is not remapped in spanish or latinamerican keyboards while Layout imitation option is activated.

- [x] I have verified that this issue hasn't yet [been reported](https://github.com/nvlgzr/fngrng/issues?q=is%3Aissue+label%3Abug)

# Steps To Reproduce
1. Set training layout to `colemak-dh`.
2. Activate `Imitate Layout` option.
3. Press `ñ` key.

```diff
+ Expected → `ñ` remapped to `o`.
- Actual → `ñ` sends `ñ`.
```

## Screenshots
![image](https://user-images.githubusercontent.com/463168/167418899-9acf85c8-d044-4109-8dbd-84d64b1e51a4.png)

## System Details
 - OS: Windows 11 Pro 21H2
 - Browser: Edge 101.0.1210.32

## Additional information
`Ñ` key keycode, as exposed to the browser using [this site](https://w3c.github.io/uievents/tools/key-event-viewer.html), is as follows:
![image](https://user-images.githubusercontent.com/463168/167419632-95d72dc4-bb54-482e-9ee8-54fe40df67cd.png)

**Comment by nvlgzr** [comment]
Thanks for the feedback, @noquierouser!

I've confirmed the issue, not just for Colemak-dh, but most of the other layouts as well. Here's the full list:

- Colemak-DH
- Colemak
- AZERTY
- Dvorak
- Tarmak
- Workman

What's nice about the LA keyboard layout is that it's identical to QWERTY, so I should be able to hack in a ñ→[X] mapping for each of the above layouts, making this a fairly trivial fix. 🌞
